/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gestaodealunos;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

import org.junit.jupiter.api.Test;

class BancoDadosAlunosTest {
	
	BancoDadosAlunos bancoDadosAlunos = new BancoDadosAlunos();
	
    @Test
    public void inserirUsuarioTeste() {
    	bancoDadosAlunos.inserirUsuario(new Usuario("Jadson", 28));
    	bancoDadosAlunos.inserirUsuario(new Usuario("Lorena", 26));
    	bancoDadosAlunos.inserirUsuario(new Usuario("Kayky", 16));
        assertNotNull(bancoDadosAlunos);
    }
    
    @Test
    void buscaUsuarioPorNomeTeste() {
    	assertEquals(bancoDadosAlunos.buscaUsuarioPorNome("Jadson"), bancoDadosAlunos.buscaUsuarioPorNome("Jadson"));
    	assertEquals(bancoDadosAlunos.buscaUsuarioPorNome("Jadson"), bancoDadosAlunos.buscaUsuarioPorNome("JaDsOn"));
    	assertEquals(bancoDadosAlunos.buscaUsuarioPorNome("Jadson"), bancoDadosAlunos.buscaUsuarioPorNome("jadson"));
    }
    
    @Test
    void excluirUsuarioTeste() {
    	Usuario usuarioExcluido = bancoDadosAlunos.buscaUsuarioPorNome("Jadson");
    	Usuario usuarioNaoExcluido = bancoDadosAlunos.buscaUsuarioPorNome("Lorena");
    	bancoDadosAlunos.excluirUsuario(usuarioExcluido);
    	assertNull(usuarioExcluido);
    }
}
